apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.app.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Random Number Generator 6 digi</title>
      <link rel="stylesheet" href="style.css">
    </head>
    <body>
      <h1>Random Number Generator</h1>
      <p>Welcome to our random number generator! Simply click the button below to generate a random 6-digit number:</p>
      <button onclick="generateRandom()">Generate Random Number</button>
      <div class="loader"></div>
      <p id="randomNumber"></p>
      <p id="errorMessage"></p>
      <script src="script.js"></script>
    </body>
    </html>